= API-Proxy Gravitee Policy

ifdef::env-github[]
image:https://ci.gravitee.io/buildStatus/icon?job=gravitee-io/generateVIHF/master["Build status", link="https://ci.gravitee.io/job/gravitee-io/job/generateVIHF/"]
image:https://badges.gitter.im/Join Chat.svg["Gitter", link="https://gitter.im/gravitee-io/gravitee-io?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
endif::[]

== Description

La policy API-Proxy est conçue pour générer un jeton VIHF signé, conforme à la spécification du CI-SIS pour une authentification indirecte.

Cette policy requête les UserInfos ProSanteConnect dans le contexte Gravitee. Elle s'articule donc particulièrement avec la policy OpenID Connect - UserInfo.

En sortie, un jeton VIHF est signé par un serveur de signature externe, puis inséré comme header SOAP dans le corps de la requête.

== Compatibilité avec Gravitee API Management

|===
|Version du plugin | Version APIM

|1.0 and upper  | 3.18.x to latest
|===

== Configuration

La policy nécessite de configurer les paramètres suivants :

|===
| Paramètre | Requis    | Description   | Type  | Défaut

.^|API Proxy certificate DN
^.^|Oui
| Le DN des certificats d'authentification client et de signature présentés au DMP (ils doivent être identiques)
^.^|chaîne de caractères
^.^|-

.^|API Proxy structure Id
^.^|Oui
|Identifiant de la structure API Proxy, enregistrée auprès du DMP
^.^|chaîne de caractères
^.^|-

.^|Nom du LPS
^.^|Oui
|Nom sous lequel l'API Proxy est enregistrée auprès du DMP
^.^|chaîne de caractères
^.^|-

.^|Version du LPS
^.^|Oui
|Numéro de version de l'API Proxy enregistré auprès du DMP
^.^|chaîne de caractères
^.^|-

.^|Numéro d'homologation du LPS
^.^|Oui
|Numéro d'homologation de l'API Proxy auprès du DMP
^.^|chaîne de caractères
^.^|-

.^|Endpoint de signature
^.^|Oui
|Endpoint du serveur de signature en XMLdsig
^.^|chaîne de caractères
^.^|http://localhost/signatures/xmldsig

.^|Signing Config Id
^.^|Oui
|Id de la configuration du serveur de signature utilisée
^.^|chaîne de caractères
^.^|-

.^|client Secret
^.^|Oui
|Secret requis pour l'accès au serveur de signature
^.^|chaîne de caractères
^.^|-

.^|System proxy
^.^|Oui
|Utiliser le system proxy
^.^|booléen
^.^|faux

.^|Use SSL
^.^|Oui
|Utiliser TLS
^.^|booléen
^.^|faux

|===




