/*
 * Dam Rest Api
 * API Rest de ledcture des DonnéesAssuranceMaladie (DAM)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: prosanteconnect@esante.gouv.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fr.ans.psc.api.client.dam.reader;

import fr.ans.psc.api.client.dam.reader.model.SimpleDams;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GetFullDamsApi
 */
@Ignore
public class GetFullDamsApiTest {

    private final GetFullDamsApi api = new GetFullDamsApi();

    /**
     * Lecture des DAMs d&#x27;un PS
     *
     * Renvoie la liste des DAMs d&#x27;un PS (nationaId)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void lectureDesDAMsTest() {
        String nationalId = null;
        SimpleDams response = api.lectureDesDAMs(nationalId);

        // TODO: test validations
    }
}
