/*
 * Dam Rest Api
 * API Rest de ledcture des DonnéesAssuranceMaladie (DAM)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: prosanteconnect@esante.gouv.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fr.ans.psc.api.client.dam.reader.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.Serializable;
/**
 * SimpleDam
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-03-01T10:44:01.736Z[GMT]")
public class SimpleDam implements Serializable{
  private static final long serialVersionUID = 1L;
  @JsonProperty("identifiantLieuDeTravail")
  private String identifiantLieuDeTravail = null;

  @JsonProperty("codeTypeIdentifiant")
  private String codeTypeIdentifiant = null;

  @JsonProperty("raisonSociale")
  private String raisonSociale = null;

  @JsonProperty("codeSpecialite")
  private String codeSpecialite = null;

  @JsonProperty("codeModeExercice")
  private String codeModeExercice = null;

  @JsonProperty("numActivite")
  private String numActivite = null;

  @JsonProperty("numAssuranceMaladie")
  private String numAssuranceMaladie = null;

  @JsonProperty("dateDebutValidite")
  private String dateDebutValidite = null;

  @JsonProperty("dateFinValidite")
  private String dateFinValidite = null;

  @JsonProperty("codeConventionnel")
  private String codeConventionnel = null;

  @JsonProperty("codeIndicateurFacturation")
  private String codeIndicateurFacturation = null;

  @JsonProperty("codeZoneIK")
  private String codeZoneIK = null;

  @JsonProperty("codeZoneTarifaire")
  private String codeZoneTarifaire = null;

  @JsonProperty("codeAgrement1")
  private String codeAgrement1 = null;

  @JsonProperty("codeAgrement2")
  private String codeAgrement2 = null;

  @JsonProperty("codeAgrement3")
  private String codeAgrement3 = null;

  @JsonProperty("habilitationFse")
  private String habilitationFse = null;

  @JsonProperty("habilitationLot")
  private String habilitationLot = null;

  public SimpleDam identifiantLieuDeTravail(String identifiantLieuDeTravail) {
    this.identifiantLieuDeTravail = identifiantLieuDeTravail;
    return this;
  }

   /**
   * Get identifiantLieuDeTravail
   * @return identifiantLieuDeTravail
  **/
  @Schema(description = "")
  public String getIdentifiantLieuDeTravail() {
    return identifiantLieuDeTravail;
  }

  public void setIdentifiantLieuDeTravail(String identifiantLieuDeTravail) {
    this.identifiantLieuDeTravail = identifiantLieuDeTravail;
  }

  public SimpleDam codeTypeIdentifiant(String codeTypeIdentifiant) {
    this.codeTypeIdentifiant = codeTypeIdentifiant;
    return this;
  }

   /**
   * Get codeTypeIdentifiant
   * @return codeTypeIdentifiant
  **/
  @Schema(description = "")
  public String getCodeTypeIdentifiant() {
    return codeTypeIdentifiant;
  }

  public void setCodeTypeIdentifiant(String codeTypeIdentifiant) {
    this.codeTypeIdentifiant = codeTypeIdentifiant;
  }

  public SimpleDam raisonSociale(String raisonSociale) {
    this.raisonSociale = raisonSociale;
    return this;
  }

   /**
   * Get raisonSociale
   * @return raisonSociale
  **/
  @Schema(description = "")
  public String getRaisonSociale() {
    return raisonSociale;
  }

  public void setRaisonSociale(String raisonSociale) {
    this.raisonSociale = raisonSociale;
  }

  public SimpleDam codeSpecialite(String codeSpecialite) {
    this.codeSpecialite = codeSpecialite;
    return this;
  }

   /**
   * Get codeSpecialite
   * @return codeSpecialite
  **/
  @Schema(description = "")
  public String getCodeSpecialite() {
    return codeSpecialite;
  }

  public void setCodeSpecialite(String codeSpecialite) {
    this.codeSpecialite = codeSpecialite;
  }

  public SimpleDam codeModeExercice(String codeModeExercice) {
    this.codeModeExercice = codeModeExercice;
    return this;
  }

   /**
   * Get codeModeExercice
   * @return codeModeExercice
  **/
  @Schema(description = "")
  public String getCodeModeExercice() {
    return codeModeExercice;
  }

  public void setCodeModeExercice(String codeModeExercice) {
    this.codeModeExercice = codeModeExercice;
  }

  public SimpleDam numActivite(String numActivite) {
    this.numActivite = numActivite;
    return this;
  }

   /**
   * Get numActivite
   * @return numActivite
  **/
  @Schema(description = "")
  public String getNumActivite() {
    return numActivite;
  }

  public void setNumActivite(String numActivite) {
    this.numActivite = numActivite;
  }

  public SimpleDam numAssuranceMaladie(String numAssuranceMaladie) {
    this.numAssuranceMaladie = numAssuranceMaladie;
    return this;
  }

   /**
   * Get numAssuranceMaladie
   * @return numAssuranceMaladie
  **/
  @Schema(description = "")
  public String getNumAssuranceMaladie() {
    return numAssuranceMaladie;
  }

  public void setNumAssuranceMaladie(String numAssuranceMaladie) {
    this.numAssuranceMaladie = numAssuranceMaladie;
  }

  public SimpleDam dateDebutValidite(String dateDebutValidite) {
    this.dateDebutValidite = dateDebutValidite;
    return this;
  }

   /**
   * Get dateDebutValidite
   * @return dateDebutValidite
  **/
  @Schema(description = "")
  public String getDateDebutValidite() {
    return dateDebutValidite;
  }

  public void setDateDebutValidite(String dateDebutValidite) {
    this.dateDebutValidite = dateDebutValidite;
  }

  public SimpleDam dateFinValidite(String dateFinValidite) {
    this.dateFinValidite = dateFinValidite;
    return this;
  }

   /**
   * Get dateFinValidite
   * @return dateFinValidite
  **/
  @Schema(description = "")
  public String getDateFinValidite() {
    return dateFinValidite;
  }

  public void setDateFinValidite(String dateFinValidite) {
    this.dateFinValidite = dateFinValidite;
  }

  public SimpleDam codeConventionnel(String codeConventionnel) {
    this.codeConventionnel = codeConventionnel;
    return this;
  }

   /**
   * Get codeConventionnel
   * @return codeConventionnel
  **/
  @Schema(description = "")
  public String getCodeConventionnel() {
    return codeConventionnel;
  }

  public void setCodeConventionnel(String codeConventionnel) {
    this.codeConventionnel = codeConventionnel;
  }

  public SimpleDam codeIndicateurFacturation(String codeIndicateurFacturation) {
    this.codeIndicateurFacturation = codeIndicateurFacturation;
    return this;
  }

   /**
   * Get codeIndicateurFacturation
   * @return codeIndicateurFacturation
  **/
  @Schema(description = "")
  public String getCodeIndicateurFacturation() {
    return codeIndicateurFacturation;
  }

  public void setCodeIndicateurFacturation(String codeIndicateurFacturation) {
    this.codeIndicateurFacturation = codeIndicateurFacturation;
  }

  public SimpleDam codeZoneIK(String codeZoneIK) {
    this.codeZoneIK = codeZoneIK;
    return this;
  }

   /**
   * Get codeZoneIK
   * @return codeZoneIK
  **/
  @Schema(description = "")
  public String getCodeZoneIK() {
    return codeZoneIK;
  }

  public void setCodeZoneIK(String codeZoneIK) {
    this.codeZoneIK = codeZoneIK;
  }

  public SimpleDam codeZoneTarifaire(String codeZoneTarifaire) {
    this.codeZoneTarifaire = codeZoneTarifaire;
    return this;
  }

   /**
   * Get codeZoneTarifaire
   * @return codeZoneTarifaire
  **/
  @Schema(description = "")
  public String getCodeZoneTarifaire() {
    return codeZoneTarifaire;
  }

  public void setCodeZoneTarifaire(String codeZoneTarifaire) {
    this.codeZoneTarifaire = codeZoneTarifaire;
  }

  public SimpleDam codeAgrement1(String codeAgrement1) {
    this.codeAgrement1 = codeAgrement1;
    return this;
  }

   /**
   * Get codeAgrement1
   * @return codeAgrement1
  **/
  @Schema(description = "")
  public String getCodeAgrement1() {
    return codeAgrement1;
  }

  public void setCodeAgrement1(String codeAgrement1) {
    this.codeAgrement1 = codeAgrement1;
  }

  public SimpleDam codeAgrement2(String codeAgrement2) {
    this.codeAgrement2 = codeAgrement2;
    return this;
  }

   /**
   * Get codeAgrement2
   * @return codeAgrement2
  **/
  @Schema(description = "")
  public String getCodeAgrement2() {
    return codeAgrement2;
  }

  public void setCodeAgrement2(String codeAgrement2) {
    this.codeAgrement2 = codeAgrement2;
  }

  public SimpleDam codeAgrement3(String codeAgrement3) {
    this.codeAgrement3 = codeAgrement3;
    return this;
  }

   /**
   * Get codeAgrement3
   * @return codeAgrement3
  **/
  @Schema(description = "")
  public String getCodeAgrement3() {
    return codeAgrement3;
  }

  public void setCodeAgrement3(String codeAgrement3) {
    this.codeAgrement3 = codeAgrement3;
  }

  public SimpleDam habilitationFse(String habilitationFse) {
    this.habilitationFse = habilitationFse;
    return this;
  }

   /**
   * Get habilitationFse
   * @return habilitationFse
  **/
  @Schema(description = "")
  public String getHabilitationFse() {
    return habilitationFse;
  }

  public void setHabilitationFse(String habilitationFse) {
    this.habilitationFse = habilitationFse;
  }

  public SimpleDam habilitationLot(String habilitationLot) {
    this.habilitationLot = habilitationLot;
    return this;
  }

   /**
   * Get habilitationLot
   * @return habilitationLot
  **/
  @Schema(description = "")
  public String getHabilitationLot() {
    return habilitationLot;
  }

  public void setHabilitationLot(String habilitationLot) {
    this.habilitationLot = habilitationLot;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SimpleDam simpleDam = (SimpleDam) o;
    return Objects.equals(this.identifiantLieuDeTravail, simpleDam.identifiantLieuDeTravail) &&
        Objects.equals(this.codeTypeIdentifiant, simpleDam.codeTypeIdentifiant) &&
        Objects.equals(this.raisonSociale, simpleDam.raisonSociale) &&
        Objects.equals(this.codeSpecialite, simpleDam.codeSpecialite) &&
        Objects.equals(this.codeModeExercice, simpleDam.codeModeExercice) &&
        Objects.equals(this.numActivite, simpleDam.numActivite) &&
        Objects.equals(this.numAssuranceMaladie, simpleDam.numAssuranceMaladie) &&
        Objects.equals(this.dateDebutValidite, simpleDam.dateDebutValidite) &&
        Objects.equals(this.dateFinValidite, simpleDam.dateFinValidite) &&
        Objects.equals(this.codeConventionnel, simpleDam.codeConventionnel) &&
        Objects.equals(this.codeIndicateurFacturation, simpleDam.codeIndicateurFacturation) &&
        Objects.equals(this.codeZoneIK, simpleDam.codeZoneIK) &&
        Objects.equals(this.codeZoneTarifaire, simpleDam.codeZoneTarifaire) &&
        Objects.equals(this.codeAgrement1, simpleDam.codeAgrement1) &&
        Objects.equals(this.codeAgrement2, simpleDam.codeAgrement2) &&
        Objects.equals(this.codeAgrement3, simpleDam.codeAgrement3) &&
        Objects.equals(this.habilitationFse, simpleDam.habilitationFse) &&
        Objects.equals(this.habilitationLot, simpleDam.habilitationLot);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identifiantLieuDeTravail, codeTypeIdentifiant, raisonSociale, codeSpecialite, codeModeExercice, numActivite, numAssuranceMaladie, dateDebutValidite, dateFinValidite, codeConventionnel, codeIndicateurFacturation, codeZoneIK, codeZoneTarifaire, codeAgrement1, codeAgrement2, codeAgrement3, habilitationFse, habilitationLot);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SimpleDam {\n");
    
    sb.append("    identifiantLieuDeTravail: ").append(toIndentedString(identifiantLieuDeTravail)).append("\n");
    sb.append("    codeTypeIdentifiant: ").append(toIndentedString(codeTypeIdentifiant)).append("\n");
    sb.append("    raisonSociale: ").append(toIndentedString(raisonSociale)).append("\n");
    sb.append("    codeSpecialite: ").append(toIndentedString(codeSpecialite)).append("\n");
    sb.append("    codeModeExercice: ").append(toIndentedString(codeModeExercice)).append("\n");
    sb.append("    numActivite: ").append(toIndentedString(numActivite)).append("\n");
    sb.append("    numAssuranceMaladie: ").append(toIndentedString(numAssuranceMaladie)).append("\n");
    sb.append("    dateDebutValidite: ").append(toIndentedString(dateDebutValidite)).append("\n");
    sb.append("    dateFinValidite: ").append(toIndentedString(dateFinValidite)).append("\n");
    sb.append("    codeConventionnel: ").append(toIndentedString(codeConventionnel)).append("\n");
    sb.append("    codeIndicateurFacturation: ").append(toIndentedString(codeIndicateurFacturation)).append("\n");
    sb.append("    codeZoneIK: ").append(toIndentedString(codeZoneIK)).append("\n");
    sb.append("    codeZoneTarifaire: ").append(toIndentedString(codeZoneTarifaire)).append("\n");
    sb.append("    codeAgrement1: ").append(toIndentedString(codeAgrement1)).append("\n");
    sb.append("    codeAgrement2: ").append(toIndentedString(codeAgrement2)).append("\n");
    sb.append("    codeAgrement3: ").append(toIndentedString(codeAgrement3)).append("\n");
    sb.append("    habilitationFse: ").append(toIndentedString(habilitationFse)).append("\n");
    sb.append("    habilitationLot: ").append(toIndentedString(habilitationLot)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
