/*
 * Dam Rest Api
 * API Rest de ledcture des DonnéesAssuranceMaladie (DAM)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: prosanteconnect@esante.gouv.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fr.ans.psc.api.client.dam.reader.model;

import java.util.Objects;
import java.util.Arrays;
import fr.ans.psc.api.client.dam.reader.model.SimpleDam;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
/**
 * SimpleDams
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-03-01T10:44:01.736Z[GMT]")
public class SimpleDams extends ArrayList<SimpleDam> implements Serializable{
  private static final long serialVersionUID = 1L;

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    return super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SimpleDams {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
