/*
 * Structure Ids Rest Api
 * Rest Api to get Structure Id for CPS system access
 *
 * OpenAPI spec version: 1.0.0
 * Contact: prosanteconnect@esante.gouv.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fr.ans.psc.api.client.structure.reader.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.Serializable;
/**
 * StructureIds
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-02-25T10:58:18.928Z[GMT]")
public class StructureIds implements Serializable{
  private static final long serialVersionUID = 1L;
  @JsonProperty("identifiantMetier")
  private String identifiantMetier = null;

  @JsonProperty("structureTechnicalId")
  private String structureTechnicalId = null;

  public StructureIds identifiantMetier(String identifiantMetier) {
    this.identifiantMetier = identifiantMetier;
    return this;
  }

   /**
   * Get identifiantMetier
   * @return identifiantMetier
  **/
  @Schema(description = "")
  public String getIdentifiantMetier() {
    return identifiantMetier;
  }

  public void setIdentifiantMetier(String identifiantMetier) {
    this.identifiantMetier = identifiantMetier;
  }

  public StructureIds structureTechnicalId(String structureTechnicalId) {
    this.structureTechnicalId = structureTechnicalId;
    return this;
  }

   /**
   * Get structureTechnicalId
   * @return structureTechnicalId
  **/
  @Schema(description = "")
  public String getStructureTechnicalId() {
    return structureTechnicalId;
  }

  public void setStructureTechnicalId(String structureTechnicalId) {
    this.structureTechnicalId = structureTechnicalId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StructureIds structureIds = (StructureIds) o;
    return Objects.equals(this.identifiantMetier, structureIds.identifiantMetier) &&
        Objects.equals(this.structureTechnicalId, structureIds.structureTechnicalId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identifiantMetier, structureTechnicalId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StructureIds {\n");
    
    sb.append("    identifiantMetier: ").append(toIndentedString(identifiantMetier)).append("\n");
    sb.append("    structureTechnicalId: ").append(toIndentedString(structureTechnicalId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
