/*
 * Structure Ids Rest Api
 * Rest Api to get Structure Id for CPS system access
 *
 * OpenAPI spec version: 1.0.0
 * Contact: prosanteconnect@esante.gouv.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fr.ans.psc.api.client.structure.reader;

import fr.ans.psc.api.client.structure.reader.model.Error;
import fr.ans.psc.api.client.structure.reader.model.StructureIds;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StructureApi
 */
@Ignore
public class StructureApiTest {

    private final StructureApi api = new StructureApi();

    /**
     * get ids endpoint
     *
     * return an StructureIds Object for the TechnicalStructureId extracted from UserInfo
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getIdsTest() {
        String structureTechnicalId = null;
        StructureIds response = api.getIds(structureTechnicalId);

        // TODO: test validations
    }
}
